export const formFields = [
  {
    type: 'text',
    id: 'firstName',
    name: 'firstName',
    label: 'First Name',
    placeholder: 'Write here',
    required: true,
  },
  {
    type: 'text',
    id: 'lastName',
    name: 'lastName',
    label: 'Last Name',
    placeholder: 'Write here',
    required: true,
  },
  {
    type: 'select',
    id: 'department',
    name: 'department',
    label: 'Department',
    required: true,
    options: [
      { value: '', label: 'Department' },
      { value: 'assimilation', label: 'Assimilation' },
      { value: 'administration', label: 'Administration' },
      { value: 'loveway_choir', label: 'Loveway Choir' },
      { value: 'media', label: 'Media' },
      { value: 'pastoral_care', label: 'Pastoral Care' },
      { value: 'partnership', label: 'Partnership' },
      { value: 'protocol', label: 'Protocol' },
      { value: 'royal_breed', label: 'Royal Breed' },
      { value: 'sanctuary_keeping', label: 'Sanctuary Keeping' },
      { value: 'sound_&_power', label: 'Sound & Power' },
      { value: 'stage_arts', label: 'Stage Arts' },
      { value: 'security_&_marshals', label: 'Security and Marshals' },
      { value: 'teens_church', label: 'Teens Church' },
      { value: 'ushering', label: 'Ushering' },
    ],
  },
  {
    type: 'file',
    id: 'liveImage',
    name: 'liveImage',
    label: 'Your Live Picture',
    accept: 'image/*',
    required: true,
  }
]